"""add unique constraint on observations

Revision ID: 60c211737295
Revises: 92804713d0c9
Create Date: 2025-07-17 03:13:05.984584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c211737295'
down_revision: Union[str, None] = '92804713d0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_station_timestamp', 'weather_observations', ['station_id', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_station_timestamp', 'weather_observations', type_='unique')
    # ### end Alembic commands ###
